#pragma once

namespace Client
{
	enum class LEVEL { STATIC, LOADING, LOGO, GAMEPLAY, TOWN, FIELD, QUEEN, GLASGAVELEN, END };

	enum class UI_LEVEL { LOADING, LOGO, GAMEPLAY, END };
	enum class PROGRESS_TYPE { LOADING, HP, STAMINA };
	enum class GAMEPLAY_UI { DEFAULT, OPTION = 1<<1, CONTROLLER = 1<<2};
	enum class PLAYER_STATE { IDLE, MOVE, ATTACK, SMASH0, SMASH1, SMASH2, SMASH3, SMASH4, GUARD, GUARD_COUNTER, HEAVYSTAND, ROLL, HIT_LIGHT, HIT_MIDDLE, HIT_STRONG, HIT_GUARD, HIT_HEAVYSTAND,GRAP, END};
	enum class STATUS_TYPE	{ HP, STAMINA, ATK, DEF };

	enum class MONSTER_STATE { SPAWN, IDLE, MOVE, ATTACK, HIT, HIT_STRONG, PATROL, JUMP, END};

	enum class ACTION_INPUT { ATTACK = 1<<0, SMASH = 1<<1, GUARD = 1<<2, ROLL = 1<<3, HEAVYSTAND = 1<<4};

	enum class ATTACK_TYPE { LIGHT, MIDDLE, STRONG };
	enum class DIR { FRONT, BACK, RIGHT, LEFT, END};

	enum class ANIM_PHASE { BEGIN, DURING, END};
	
	enum class ITEM_TYPE { WEAPON, ARMOR, OTHERS };
	enum class WEAPON_TYPE { SWORD, SHILED, END};
	enum class ARMOR_TYPE { HEAD, UPPER, LOWER, HAND, FOOT, END};
	enum class ARMOR_STATE { DEFAULT, BROKEN, END };

	enum class COLLIDER_OWNER { PLAYER, MONSTER, OBJECT, END };
	enum class COLLIDER_CHANNEL { BOUNDING, BODY, ATTACK, HIT, GRAP, INTERACTION, END };

	enum class MONSTER_STATE_TYPE { VAMPIRE, VAMPIRE_ELDER, QUEEN, GLASGAVELEN };
	enum class VAMPIRE_STATE { SPAWN, IDLE, MOVE, ATTACK, HIT, HIT_STRONG, PATROL, DEAD, DEAD_STRONG, END};
	enum class QUEEN_STATE { SPAWN, IDLE, MOVE, TURN, ATTACK, ATTACK_NEAR, JUMP, BURROW, HIT, DOWN, DEAD, END };
	enum class GAVELEN_STATE { SPAWN, CUTSCENE, IDLE, MOVE, TURN, ATTACK, ATTACK_NEAR, DESEND, RAGE, RAGE_DESEND, HANG, GRAP, HIT, DOWN, WINGBREAK, DEAD, END };
	enum class MONSTER_TYPE { VAMPIRE_BASIC, VAMPIRE_ELDER, VAMPIRE_ROYAL, QUEEN, GLASGAVELEN };

	enum class NOTIFY_TYPE { ON, OFF};
	enum class EFFECT_TYPE { STATIC, BILLBAORD, PREFAB, TRAIL, DISTORTION };
	enum class TRAIL_TYPE { STATIC, BILLBOARD};

	enum class SHADER_VTXPOSTEX { DEFAULT, ALPHABLEND, PROGRESSBAR, LOADINGPOINT, TRAIL, BLEND_BAR, BLEND, COLOR, DAMAGE_FONT};
	enum class SHADER_VTXNORTEX { DEFAULT };
	enum class SHADER_VTXCUBE { SKY };

	enum class SHADER_VTXANIMMESH { DEFAULT, WIRE, COLOR_MASKING, SHADOW};
	enum class SHADER_VTXMESH { DEFAULT, WIRE, COLOR_MASKING, MAP_OBJECT, SHADOW};
	
	enum class SHADER_PARTICLE { DEFAULT, RING};
	enum class SHADER_POINTPARTICE { DEFAULT, SPRITE, ROTATE, LOOP};
	enum class SHADER_TRAIL { DEFAULT, EMISSIVE };
	enum class SHADER_DISTORTION { DEFAULT, ROTATE};

	enum class DYEING_MATERIAL { CLOTH, LEATHER, WEAPON_METAL, ARMOR_METAL, NONE };
	enum class DYEING_PART { R, G, B, END};

	enum class SOUND_CHANNEL { PLAYER_VOICE, PLAYER_ATTACK, BGM, OTHERS, END};

}
