#pragma once

namespace Client
{
	enum class LEVEL { STATIC, LOADING, LOGO, GAMEPLAY, TOWN, FIELD, QUEEN, GLASGAVELEN, END };

	enum class UI_LEVEL { LOADING, LOGO, GAMEPLAY, END };
	enum class PROGRESS_TYPE { LOADING, HP, STAMINA };
	enum class GAMEPLAY_UI { DEFAULT, OPTION = 1<<1, CONTROLLER = 1<<2};
	enum class PLAYER_STATE { IDLE, MOVE, ATTACK, SMASH0, SMASH1, SMASH2, SMASH3, SMASH4, GUARD, GUARD_COUNTER, HEAVYSTAND, ROLL, HIT_LIGHT, HIT_MIDDLE, HIT_STRONG, HIT_GUARD, HIT_HEAVYSTAND, END};

	enum class MONSTER_STATE { SPAWN, IDLE, MOVE, ATTACK, HIT, HIT_STRONG, PATROL, JUMP, END};

	enum class ACTION_INPUT { ATTACK = 1<<0, SMASH = 1<<1, GUARD = 1<<2, ROLL = 1<<3, HEAVYSTAND = 1<<4};

	enum class ATTACK_TYPE { LIGHT, MIDDLE, STRONG };
	enum class HIT_DIR { FRONT, BACK, RIGHT, LEFT, END};

	enum class ANIM_PHASE { BEGIN, DURING, END};
	
	enum class ITEM_TYPE { WEAPON, ARMOR, OTHERS };
	enum class WEAPON_TYPE { SWORD, SHILED, END};
	enum class ARMOR_TYPE { HEAD, UPPER, LOWER, HAND, FOOT, END};
	enum class ARMOR_STATE { DEFAULT, BROKEN, END };

	enum class COLLIDER_OWNER { PLAYER, MONSTER, OBJECT, END };
	enum class COLLIDER_CHANNEL { BOUNDING, BODY, ATTACK, HIT, END };

	enum class MONSTER_TYPE { VAMPIRE_BASIC, VAMPIRE_ELDER, VAMPIRE_ROYAL, QUEEN, GLASGAVELEN };
}
